### PR TITLE
Updated to latest Revery (adapted to breaking changes)

### PR DESCRIPTION
**Pull request by geoffder**
I've brought the Revery dependency up to date and adapted to the breaking changes with respect to font details no longer being included in Style.t (and a handful of other super minor ones). A new type `font_info` which carries the family, size, and weight characteristics has been added to Attributes, so that the font related details can be passed around and handled alongside the style data.

### CODE REVIEW

**Comment by geoffder** [comment]
Alternative to the font_info route, I've made a [branch](/geoffder/bonsai_revery/tree/kind_spec) that uses a `kind` field in attributes that can hold specifications specific to certain node types, rather than cluttering the attributes record itself with a number of fields that are only relevant to single node subtypes. Along with this, I've also added a basic image node component based on your implementation of the text node. (Bonsai tree png added to the title box in todoMVC to demo it).

**Comment by ozanvos** [comment]
This looks really good, thanks for doing this! I'll play with it a bit and merge early next week.

**Comment by geoffder** [comment]
The branch or the original changes? IShould I merge the branch (linked in previous comment) in to the main? Seems like it is a decent way to go about it anyway (the kind field), but I'm curious to hear your thoughts. I also added in the textNode properties that I forgot about (and included them in `Attributes.update_text_node` in the `kind_spec` branch.

Thanks for taking a look, and for making this in the first place!

**Comment by ozanvos** [comment]
Agreed, let's make that branch a part of this.

**Comment by geoffder** [comment]
Ok will do.

**Comment by geoffder** [comment]
On top of this stuff, I've got a [scroll_view branch](https://github.com/geoffder/bonsai_revery/tree/scroll_view) going with a number of components implemented (and demoed in the todoMVC).

The components are: Resizable, Draggable, Slider, and ScrollView. The former of which all compose to to create the latter. It's not perfect yet of course, but they seem to work quite well as building blocks. They're just piled up at the end of `components.ml` right now for simplicities sake.

**Comment by ozanvos** [comment]
Thanks a lot for this, looks great! I'm looking forward to the new components too!

**Pull request merged**
